services:
  - type: web
    name: expense-calendar
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        value: 11.142.154.110
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: with_ghhdklifczfuchhv
      - key: DB_PASSWORD
        value: "v8Diue5xp#SCP!"
      - key: DB_NAME
        value: l65360zd
      - key: ADMIN_USERNAMES
        value: admin
